<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>AudioPersonal</AssemblyName>
    <RootNamespace>AudioPersonal</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <ApplicationIcon>src\AudioPersonal.ico</ApplicationIcon>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="src\AudioPersonal.cs" />
    <Compile Include="src\InternalPlayer.cs" />
    <None Include="app.config" />
    <Content Include="src\AudioPersonal.ico" />
    <Reference Include="NAudio">
      <HintPath>lib\NAudio.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
